### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by naor020066** [ShouxTech/RobloxQuickXecute#3]
The program creates a 32bit dll while roblox is a 64bit game, which prevents it from being injected into roblox. And the program can't be produce 64bit dlls because it's using a __asm section which is only supported in 32bit.

**Comment by Silme94** [comment]
try maybe the microsoft version

**Comment by ShouxTech** [comment]
This program was created before the whole Hyperion anti-cheat stuff that Roblox implemented and so it was intended to be used on the 'normal' version of the Roblox client which was 32 bit (I don't know if its 64 bit now). I believe you're also talking about the Microsoft Store version of Roblox which is 64 bit but this program was never made for the Microsoft Store version.
